workflows:
  android-workflow:
    name: Android Release
    max_build_duration: 60
    environment:
      flutter: stable
      android_signing:
        - stayfix_upload_keystore
      vars:
        PACKAGE_NAME: "com.rezzaky.stayfix"
    scripts:
      - name: Generate .env file
        script: |
          echo "VPS_MEDIA_BASE_URL=$VPS_MEDIA_BASE_URL" >> .env
          echo "STAYFIX_EMAIL_SECRET=$STAYFIX_EMAIL_SECRET" >> .env
          echo "STAYFIX_EMAIL_WEB_APP_URL=$STAYFIX_EMAIL_WEB_APP_URL" >> .env
          echo "GOOGLE_MAPS_API_KEY=$GOOGLE_MAPS_API_KEY" >> .env

      - name: Get Flutter packages
        script: flutter pub get

      - name: Build AAB
        script: |
          flutter build appbundle --release \
            --build-name=1.0.0 \
            --build-number=$(($(google-play get-latest-build-number \
              --package-name "$PACKAGE_NAME" \
              --tracks="$GOOGLE_PLAY_TRACK") + 1))

    artifacts:
      - build/**/outputs/**/*.aab
      - build/**/outputs/**/mapping.txt
      - flutter_drive.log

    publishing:
      google_play:
        credentials: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
        track: internal
        submit_as_draft: true
